name: preblo
description: Presentation & business logic component.
version: 0.1.5
repository: https://github.com/hereismhtm/preblo/tree/master

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1
