name: preblo
description: Presentation & business logic component.
version: 0.0.2
repository: https://github.com/hereismhtm/preblo/tree/master

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.0
